FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

# Modificar esta línea para incluir nodemon
RUN npm install && npm install nodemon -g

COPY . .

EXPOSE 3000

CMD ["npx", "nodemon", "src/app.js"]